export const TRANSACTION_TYPES = {
  EARN: 'EARN',
  SPEND: 'SPEND',
  HOLD: 'HOLD',
  RELEASE: 'RELEASE',
  REFUND: 'REFUND',
  BONUS: 'BONUS',
  PENALTY: 'PENALTY'
};

export const SESSION_STATUS = {
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  DISPUTED: 'DISPUTED',
  NO_SHOW: 'NO_SHOW'
};

export const SESSION_MODES = {
  ONLINE: 'ONLINE',
  IN_PERSON: 'IN_PERSON',
  BOTH: 'BOTH'
};

export const SKILL_LEVELS = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED'
};

export const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

export const NOTIFICATION_TYPES = {
  SESSION_REQUESTED: 'SESSION_REQUESTED',
  SESSION_ACCEPTED: 'SESSION_ACCEPTED',
  SESSION_REJECTED: 'SESSION_REJECTED',
  SESSION_CANCELLED: 'SESSION_CANCELLED',
  SESSION_CONFIRMED: 'SESSION_CONFIRMED',
  SESSION_COMPLETED: 'SESSION_COMPLETED',
  CREDIT_EARNED: 'CREDIT_EARNED',
  CREDIT_SPENT: 'CREDIT_SPENT',
  CREDIT_RELEASED: 'CREDIT_RELEASED',
  RATING_RECEIVED: 'RATING_RECEIVED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  DISPUTE_FILED: 'DISPUTE_FILED'
};

export const INITIAL_CREDITS = 3;
export const CREDITS_PER_HOUR = 1;
